name: Labeler
on:
  - pull_request_target

jobs:
  triage:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Apply PR labels
        uses: actions/labeler@master
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
