name: Test
on: [push]

jobs:
  test:
    name: Build and run tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Node 17.x
        uses: actions/setup-node@v2
        with:
          version: 17.x

      - name: Install Dependencies and build (with cache)
        uses: bahmutov/npm-install@v1

      - name: Test
        run: npm run test
